dist: bionic
language: elixir

elixir:
  - "1.8"
  - "1.9"
  - "1.10"

opt_release:
  - "20.3.8"
  - "21.2"
  - "22.3"
  - "23.0"

jobs:
  exclude:
    - elixir: "1.8"
      otp_release: "23.0"
    - elixir: "1.9"
      otp_release: "23.0"
    - elixir: "1.10"
      otp_release: "20.3.8"

env:
  - MIX_ENV=test

before_script:
  - mix local.rebar --force

script: mix coveralls.travis

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
